---

- name: install auxilary packets
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - apparmor

- name: fetch docker apt key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add docker repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

- name: Refresh cache
  apt:
    update_cache: yes

- name: Update distro
  apt:
    name: "*"
    state: latest

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: install docker
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install docker compose
  pip:
    name:
    - docker
    - docker-compose

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/docker-compose.service
    content: |
      [Unit]
      Description=Docker Compose Service
      Requires=docker.service
      After=docker.service
      [Service]
      Type=oneshot
      RemainAfterExit=true
      WorkingDirectory=/srv
      ExecStart=/usr/local/bin/docker-compose up -d --remove-orphans
      ExecStop=/usr/local/bin/docker-compose down
      [Install]
      WantedBy=multi-user.target

- name: Systemd service activation
  systemd:
    name: docker-compose.service
    enabled: true
    daemon_reload: true
